
You need to run those `taskkill` commands in a **Windows PowerShell** or **Command Prompt (CMD)** window.

---

### 🔹 Steps:

1. **Close VS Code completely** first.

2. Open either:

   * **PowerShell** → Press `Win + X`, choose **Windows PowerShell** (or **Terminal**).
   * **Command Prompt (CMD)** → Press `Win + R`, type `cmd`, hit Enter.

3. In that window, run these commands one by one:

   ```powershell
   taskkill /F /IM python.exe /T
   taskkill /F /IM pythonw.exe /T
   ```

   * If Python is running in the background, it will kill the process.
   * If it’s not running, you’ll see a message like *"No instance found"* → that’s fine.

4. Now go back to your project folder (`D:\Vfile\coding\Python\`) and delete the `venv` folder:

   ```powershell
   rmdir venv -Recurse -Force
   ```

---

👉 After that, you can safely recreate the environment.

Do you want me to write you the **exact full sequence of commands** to copy-paste (from killing Python → deleting `venv` → making a new one → installing numpy), so you don’t need to type step by step?


Those errors just mean there were **no Python processes running**, so nothing was locking your `.pyd` / `.exe` files anymore. 🎉

---

### Next Step: Delete the old `venv`

Now go back to your project folder and remove the broken venv:

```powershell
cd D:\Vfile\coding\Python
rmdir venv -Recurse -Force
```

(if it still complains, you can also delete it manually via File Explorer).

---

### Then: Recreate a fresh environment

Once the `venv` folder is gone, create a new one:

```powershell
python -m venv venv
```

Activate it:

```powershell
.\venv\Scripts\Activate.ps1
```

And install numpy + jupyter:

```powershell
pip install numpy jupyter
```

pip install --upgrade pip
pip install jupyter ipykernel numpy pandas matplotlib


---

👉 Do you want me to bundle all of this into a **one-shot script** you can paste into PowerShell, so it cleans old `venv`, recreates it, activates it, and installs everything automatically?


In [31]:
import numpy as np

In [32]:
arr = np.array([[1, 2], [4, 6]])
arr

array([[1, 2],
       [4, 6]])

In [33]:
arr[0]

array([1, 2])

In [34]:
arr[1]

array([4, 6])

In [35]:
arr[1][0]

np.int64(4)

In [36]:
arr[0][1]

np.int64(2)

array----asarray---[anyarray in this it first observe is data present iny type of an array if it not then it conver]

ndarray is parent class as matrix is subclass

In [37]:
issubclass(np.ndarray,np.matrix)

False

In [38]:
arr

array([[1, 2],
       [4, 6]])

In [39]:
a=arr

In [40]:
b= np.copy(arr)

In [41]:
arr[0][0]=45

In [42]:
a

array([[45,  2],
       [ 4,  6]])

In [43]:
b

array([[1, 2],
       [4, 6]])

arrays are mutabel

In [44]:
arr[-1]

array([4, 6])

In [45]:
arr[-0][-1]

np.int64(2)

In [46]:
arr[-1][-1]

np.int64(6)

In [47]:
for i in arr:
  print(i)

[45  2]
[4 6]


In [48]:
for i in b:
  print(i)

[1 2]
[4 6]


fromfunction(lamda i,j:i==j,(4,4))---- it create the array using  parameter 

In [49]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [50]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

List comprehension in Python offers a concise and efficient way to create new lists based on existing iterables (like lists, tuples, strings, or ranges). It provides a more compact and often more readable alternative to traditional for loops for list creation and manipulation.

In [51]:
#Creating a list of squares.
squares = [x**2 for x in range(5)]
squares


[0, 1, 4, 9, 16]

In [52]:
modified_list = [x * 2 if x > 5 else x for x in range(10)]
modified_list

[0, 1, 2, 3, 4, 5, 12, 14, 16, 18]

The range() function is a built-in Python function that returns a range object. This object represents an immutable, lazy sequence of numbers that is used for iterating a specific number of times in for loops. 

In [53]:
mod = [] 
for x in range(10):
  if(x>5):
    x*2
  else:
    x
mod

[]

In [54]:
mod = [] 
for x in range(10):
  if(x>5):
    mod.append(x*2)
  else:
    mod.append(x)
mod

[0, 1, 2, 3, 4, 5, 12, 14, 16, 18]

In [55]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [56]:
np.fromfunction(lambda i,j:i+j,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

np.from is the prefix for a family of functions that are used to create arrays from various data sources. These functions allow you to construct NumPy arrays from iterables, buffers, and other data structures. 
from array creation functions
Here are some of the most common np.from functions:
np.fromiter()
Creates a new one-dimensional array from an iterable object, like a list, tuple, or generator. The dtype must be specified. 

In [57]:
iterable = (x*x for x in range(5))
arr = np.fromiter(iterable, dtype=float)
print(arr)

[ 0.  1.  4.  9. 16.]


np.frombuffer()
Interprets a buffer as a one-dimensional array. This is useful for working with binary data, such as a bytes object. 

In [58]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

24-08-2025

In [59]:
arr2 = np.array([(1,2,3),(4,5,6)])
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr3)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [65]:
print(arr2[0])
print(arr2[1])

[1 2 3]
[4 5 6]


In [ ]:
print(arr2[0][2])
print(arr2[1,1])

3
5


In [ ]:
print(type(arr2))

<class 'numpy.ndarray'>


NameError: name 'dtype' is not defined

In [68]:
arr3[1]

array([4, 5, 6])

In [69]:
arr3[0][2]

np.int64(3)

In [71]:
arr3[0,2]

np.int64(3)

In [77]:
arr2.ndim

2

In [78]:
arr3.ndim

2

In [ ]:
ceil(arr2)

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
import numpy as np
result = np.ceil(arr3)
print(result)

[[1 2 3]
 [4 5 6]]
